name: bluelinky
adopt-info: bluelinky
summary: An unofficial nodejs API wrapper for Hyundai BlueLink
description: | 
  A snap for the unofficial nodejs API wrapper for Hyundai BlueLink - "bluelinky"
  
  Read the docs: https://hacksore.github.io/bluelinky-docs/docs/getting-started
  
  To start from your terminal, type: bluelinky

license: MIT

base: core20
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  bluelinky:
    command: bin/npm run debug
    plugs:
      - home
      - network

parts:
  bluelinky:
    source: https://github.com/Hacksore/bluelinky
    source-type: git
    plugin: npm
    npm-node-version: "18.1.0"    
    source-type: git
    build-snaps:
      - node/18/stable
    stage-snaps:
      - node/18/stable
  
    override-build: |
      npm config set unsafe-perm true
      npm install -g --prefix "${SNAPCRAFT_PART_INSTALL}" --include=dev bluelinky 
      snapcraftctl build
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
